let suggestions = [
    "A K Antony",
    "Abhishek Banerjee",
    "Akhilesh Yadav",
    "Amit Shah",
    "Anand Sharma",
    "Anupriya Patel",
    "Anurag Thakur",
    "Arun Jaitley",
    "Arvind Kejriwal",
    "Asaduddin Owaisi",
    "Ashok Gehlot",
    "B S Yeddyurappa",
    "Bhagwant Mann",
    "Bhupesh Baghel",
    "Biplab Kumar Deb",
    "Babul Supriyo",
    "Captain Amarinder Singh",
    "Chirag Paswan",
    "Devendra Fadnavis",
    "Dharmendra Pradhan",
    "Digvijaya Singh",
    "Divya Spandana",
    "Derek O'Brien",
    "Edappadi K Palaniswami",
    "Farooq Abdullah",
    "Ghulam Nabi Azad",
    "Giriraj Singh",
    "H D Deve Gowda",
    "HD Kumaraswamy",
    "Hardik Patel",
    "Harish Rawat",
    "Harsh Vardhan",
    "Harsimrat Kaur Badal",
    "Hemant Soren",
    "Himanta Biswa Sarma",
    "Jagat Prakash Nadda",
    "Jairam Ramesh",
    "Jitendra Singh",
    "Jyotiraditya Scindia",
    "KCR",
    "Kamal Haasan",
    "Kamal Nath",
    "Kanimozhi",
    "Kapil Sibal",
    "Kiren Rijiju",
    "Lal Krishna Advani",
    "Lalu Prasad Yadav",
    "M K Alagiri",
    "M K Stalin",
    "Mamata Banerjee",
    "Maneka Gandhi",
    "Mani Shankar Aiyar",
    "Manmohan Singh",
    "Manpreet Badal",
    "Mayawati",
    "Mehbooba Mufti",
    "Mulayam Singh Yadav",
    "Murli Manohar Joshi",
    "Mallikarjun Kharge",
    "N Chandrababu Naidu",
    "Naveen Patnaik",
    "Navjot Singh Sidhu",
    "Nirmala Sitharaman",
    "Nitin Gadkari",
    "Nitish Kumar",
    "Narendra Modi",
    "O Panneerselvam",
    "Omar Abdullah",
    "P Chidambaram",
    "Paresh Rawal",
    "Pinarayi Vijayan",
    "Piyush Goyal",
    "Priyanka Gandhi",
    "Radha Mohan Singh",
    "Rahul Gandhi",
    "Raj Babbar",
    "Raj Thackeray",
    "Rajnath Singh",
    "Rajyavardhan Singh Rathore",
    "Ram Madhav",
    "Ram Vilas Paswan",
    "Ramdas Athawale",
    "Randeep Surjewala",
    "Ravi Shankar Prasad",
    "Sachin Pilot",
    "Sanjeev Balyan",
    "Sharad Pawar",
    "Sharad Yadav",
    "Shashi Tharoor",
    "Shatrughan Sinha",
    "Shivraj Singh Chouhan",
    "Sitaram Yechury",
    "Smriti Irani",
    "Sonia Gandhi",
    "Subramanian Swamy",
    "Sushma Swaraj",
    "TTV Dhinakaran",
    "Thawar Chand Gehlot",
    "Tarun Gogoi",
    "Uddhav Thackeray",
    "Uma Bharti",
    "V K Singh",
    "Varun Gandhi",
    "Vasundhara Raje",
    "Vijay Goel",
    "Vinay Katiyar",
    "Y S Jaganmohan Reddy",
    "Yashwant Sinha",
    "Yogi Adityanath",
    
];
