let suggestions = [
    "A K Antony",
    "Abhishek Banerjee",
    "Ahmed Patel",
    "Ajit Singh",
    "Akhilesh Yadav",
    "Amit Shah",
    "Anand Sharma",
    "Anupriya Patel",
    "Anurag Thakur",
    "Arun Jaitley",
    "Arvind Kejriwal",
    "Asaduddin Owaisi",
    "Ashok Gehlot",
    "B S Yeddyurappa",
    "Bhagwant Mann",
    "Bhupesh Baghel",
    "Biplab Kumar Deb",
    "Babul Supriyo",
    "Captain Amarinder Singh",
    "Chirag Paswan",
    "Devendra Fadnavis",
    "Dharmendra Pradhan",
    "Digvijaya Singh",
    "Divya Spandana",
    "Derek O'Brien",
    "Edappadi K Palaniswami",
    "Arvind Kejriwal",
    "Asaduddin Owaisi",
    "Ashok Gehlot",
    "B S Yeddyurappa",
    "Bhagwant Mann",
    "Bhupesh Baghel",
    "Biplab Kumar Deb",
    "Babul Supriyo",
    "Captain Amarinder Singh",
    "Chirag Paswan",
    "Devendra Fadnavis",
    "Dharmendra Pradhan",
    "Digvijaya Singh",
    "Divya Spandana",
    "Derek O'Brien",
    "Edappadi K Palaniswami",
    
    
];
